import type { InvitationData } from "./types";

export const dummyData: InvitationData = {
  slug: "preview",
  theme: "emerald-gold",
  expiredAt: "2027-01-01T00:00:00Z",
  openingText: "The Wedding Of",

  groom: {
    nickname: "Reza",
    fullName: "Muhammad Reza Pratama",
    parents: "Putra dari Bapak Ahmad & Ibu Siti",
    photo: undefined,
  },
  bride: {
    nickname: "Aulia",
    fullName: "Aulia Rahma Dewi",
    parents: "Putri dari Bapak Hendra & Ibu Rina",
    photo: undefined,
  },

  events: [
    {
      title: "Akad Nikah",
      date: "Sabtu, 12 April 2025",
      time: "08.00 — 09.00 WIB",
      location: "Masjid Al-Ikhlas",
      address: "Jl. Melati No. 12, Surabaya",
      icon: "akad",
      mapsEmbedSrc: "https://www.google.com/maps?q=-7.257472,112.752090&z=17&output=embed",
      mapsUrl: "https://maps.google.com",
    },
    {
      title: "Resepsi",
      date: "Sabtu, 12 April 2025",
      time: "10.00 — 14.00 WIB",
      location: "Gedung Serbaguna Bahagia",
      address: "Jl. Melati No. 12, Surabaya",
      icon: "reception",
      mapsEmbedSrc: "https://www.google.com/maps?q=-7.257472,112.752090&z=17&output=embed",
      mapsUrl: "https://maps.google.com",
    },
  ],

  photos: [],

  banks: [
    { bank: "Bank BCA", number: "1234567890", accountName: "a.n. Muhammad Reza Pratama" },
    { bank: "Bank Mandiri", number: "0987654321", accountName: "a.n. Aulia Rahma Dewi" },
  ],

  musicUrl: "/music/background.mp3",
  rsvpEnabled: true,
  wishesEnabled: true,
};

export const themes = [
  {
    id: "emerald-gold",
    name: "Emerald Gold",
    description: "Elegan dengan nuansa hijau zamrud dan emas. Cocok untuk pernikahan mewah dan sakral.",
    tags: ["Elegan", "Mewah"],
    category: "Elegan",
    palette: ["#0A3D2E", "#D4A853", "#EAD18F"],
    available: true,
    hidden: true,
    price: 130000,
    tier: "Premium",
  },
  {
    id: "ylang-ylang",
    name: "Ylang Ylang",
    description: "Hangat dan botanical dengan krem gading, hijau hutan, dan emas. Sentuhan alam yang elegan.",
    tags: ["Natural", "Botanical"],
    category: "Natural",
    palette: ["#FAF7F2", "#3D5A45", "#C4975A"],
    available: true,
    price: 60000,
    tier: "Basic",
  },
  {
    id: "rose-blush",
    name: "Rose Blush",
    description: "Romantis dengan warna pink lembut dan rosegold accent. Feminin dan hangat.",
    tags: ["Romantis", "Feminin"],
    category: "Romantis",
    palette: ["#FDF6F6", "#C17A8F", "#C99070"],
    available: true,
    price: 60000,
    tier: "Basic",
  },
  {
    id: "midnight-blue",
    name: "Midnight Blue",
    description: "Modern dan elegan dengan deep blue navy dan silver. Kesan mewah dan profesional.",
    tags: ["Modern", "Formal"],
    category: "Modern",
    palette: ["#0B1221", "#4A9EE8", "#DDE3EE"],
    available: true,
    price: 95000,
    tier: "Elegant",
  },
  {
    id: "galaxy",
    name: "Galaxy",
    description: "Romantis berbintang dengan star field 3D, nebula gradient, dan partikel orbit yang memukau.",
    tags: ["Modern", "3D Effect"],
    category: "Modern",
    palette: ["#04040E", "#8B5CF6", "#E879A0"],
    available: true,
    price: 95000,
    tier: "Elegant",
  },
  {
    id: "jawa-klasik",
    name: "Jawa Klasik",
    description: "Adat Jawa dengan animasi janur, motif batik, dan gunungan wayang. Sakral dan berbudaya.",
    tags: ["Tradisional", "Adat Jawa"],
    category: "Tradisional",
    palette: ["#0E0600", "#D4A020", "#8B1515"],
    available: true,
    price: 130000,
    tier: "Premium",
  },
  {
    id: "sunda-klasik",
    name: "Sunda Klasik",
    description: "Adat Sunda dengan motif mega mendung, ornamen kujang, dan nuansa bumi yang hangat.",
    tags: ["Tradisional", "Adat Sunda"],
    category: "Tradisional",
    palette: ["#0A0500", "#C89020", "#B05020"],
    available: true,
    price: 130000,
    tier: "Premium",
  },
  {
    id: "sakura-bloom",
    name: "Sakura Bloom",
    description: "Kelopak sakura jatuh dalam efek 3D nyata, estetika Jepang yang bersih dan romantis.",
    tags: ["3D Effect", "Romantis"],
    category: "Romantis",
    palette: ["#FDF8F9", "#D4708A", "#C89050"],
    available: true,
    price: 95000,
    tier: "Elegant",
  },
  {
    id: "cinematic",
    name: "Cinematic",
    description: "Layar penuh sinematik, tipografi dramatis besar, dan transisi seperti trailer film.",
    tags: ["Modern", "Sinematik"],
    category: "Modern",
    palette: ["#080808", "#F0EAE0", "#C8A878"],
    available: true,
    price: 130000,
    tier: "Premium",
  },
];
